version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        # Ignore only new versions for 4.x and 5.x
        versions: ["13.x", "14.x"]


  - package-ecosystem: "composer"
    directory: "/wordpress/base"
    # Check for updates once a week
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/wordpress/base"
    # Check for updates once a week
    schedule:
      interval: "weekly"
