name: 'Composer (php-actions)'
description: 'Use the Composer CLI in your Github Actions.'
inputs:
  directory:
    description: 'Directory to install'
    required: true
outputs:
  time:
    description: 'The time the action was run'
runs:
  using: 'docker'
  image: 'composer:latest'
  args:
    - install
    - -d
    - ${{ inputs.directory }}
branding:
  icon: 'package'
  color: 'purple'