name: 'Composer (php-actions)'
description: 'Use the Composer CLI in your Github Actions.'
inputs:
  command:
    description: 'Composer command to run'
    required: true
    default: install
outputs:
  time:
    description: 'The time the action was run'
runs:
  using: 'docker'
  image: 'composer:latest'
  args:
    - install
    - --no-progress
    - -d
    - wordpress
branding:
  icon: 'package'
  color: 'purple'