version: 1

update_configs:
  - package_manager: "javascript"
    update_schedule: "live"
    directory: "/"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "php:composer"
    directory: "/wordpress/base"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
