version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/nodejs"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "php:composer"
    directory: "/wordpress"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "docker"
    directory: "/wordpress"
