on:
  push: {}

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Mount npm cache
        uses: actions/cache@v3.0.11
        with:
          path: "/home/runner/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Cache Composer Downloads
        uses: actions/cache@v3.0.11
        with:
          path: "/home/runner/.cache/composer/files"
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Wordpress bedrock dependencies
        uses: ./.github/actions/composer
        with:
          directory: wordpress/base_bedrock/repo

      - name: Install Wordpress plugins dependencies
        uses: ./.github/actions/composer
        with:
          directory: wordpress/base_plugins

      - name: Mount bazel cache
        uses: actions/cache@v3.0.11
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion') }}-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-bazel--${{ hashFiles('.bazelversion') }}

      - name: Build
        run: |
          npx bazel build //...
