on:
  push: {}

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Mount npm cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.npm"
          key: npm

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: wordpress/base_bedrock/vendor
          key: ${{ runner.OS }}-wordpress-build-${{ hashFiles('wordpress/**/composer.lock') }}

      - name: Install bedrock Composer packages dependencies
        uses: php-actions/composer@v1
        with:
          command: composer
          args: install -d wordpress/base_bedrock/repo

      - name: Install wordpress plugins Composer packages dependencies
        uses: php-actions/composer@v1
        with:
          command: composer
          args: install -d wordpress/base_plugins

      - name: Build
        run: |
          npx bazel build //nodejs/...
