on:
  push: {}

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Mount npm cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.npm"
          key: npm

      - name: Get Composer Cache Directory
        id: composer-cache
        working-directory: ./wordpress/base_bedrock
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Install Wordpress bedrock dependencies
        uses: ./.github/actions/composer
        with:
          directory: wordpress/base_bedrock/repo

      - name: Install Wordpress plugins dependencies
        uses: ./.github/actions/composer
        with:
          directory: wordpress/base_plugins

      - name: Build
        run: |
          npx bazel build //...
