name: CI

on:
  push: {}

jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Mount npm cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.npm"
          key: npm

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Install npm dependencies
        run: |
          npm ci --prefix nodejs

      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //nodejs/...

  build-wordpress:
    needs: build-nodejs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: wordpress/vendor
          key: ${{ runner.OS }}-wordpress-build-${{ hashFiles('**/composer.lock') }}

      - name: Install Wordpress dependencies
        uses: php-actions/composer@v1
        with:
          command: install -d ./wordpress
