on:
  push:
    paths:
      - 'nodejs/**'
      - '.bazelignore'
      - 'package.json'
      - 'package-lock.json'
      - 'BUILD'
      - 'WORKSPACE'

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Mount npm cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.npm"
          key: npm

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npx bazel build //nodejs/...
